config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  get 'users' => 'users#index'
  get "gweets" => 'gweets#index'
  get 'users/:id' => 'users#show', as: :user_show
  get 'users/:id/gweets' => 'gweets#new', as: :user_gweets
  post 'users/:id/gweets' => 'gweets#create'
  post 'users' => 'users#create'

end

app/models/gweet.rb
class Gweet<ActiveRecord::Base

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :gweets, dependent: :destroy
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    user ||= User.find_by(id:session[:user_id])
  end

  helper_method :current_user

end

app/controllers/gweets_controller.rb
class GweetsController < ApplicationController

  def index
    @gweets = Gweet.all
  end

  def new
  end

  def create
  	@user = User.find_by(id: params[:id])

  	@gweet = @user.gweets.create(gweet_params)

  	if @gweet
  	  redirect_to user_show_path(@user)
  	end
  end

private

  def gweet_params
    params.require(:gweet).permit(
      :content
    	)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user  = User.find_by(email:params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to users_path
    else
      @sign_in_error = "Username / password combination is invalid"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


  def home
    @user = User.new
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  	@users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def show
  	@user = User.find_by(id: params[:id])
  	@gweet = Gweet.new
  	@gweets = @user.gweets
  end


private

  def user_params
    params.require(:user).permit(
    :username,
    :email,
    :avatar_url,
    :password,
    :password_confirmation
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gweets/index.html.erb
<% @gweets.each do |gweet| %>
Created: <%= gweet.created_at %>
<p>
	<p><%= gweet.content  %></p>
by <%= gweet.user.username  %> 
</p>
<hr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if instance.errors.any? %>

<div class="alert alert-danger">
  <h2><%= pluralize(instance.errors.count,"error") %></h2>
  prevented this <%= instance.class %> from being saved:

  <ul>
    <% instance.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  </ul>
</div>
<% end %>

app/views/static_pages/home.html.erb
<h3>Welcome to gWitter</h3>

<%= link_to "Show Users", users_path %> |
<%= link_to "All gWeets Ever!", gweets_path %>

<% if current_user %>
  <h1><%= current_user.username %></h1>
  <h2><%= link_to 'Sign out', signout_path %>  </h2>
<% else %>
  <h2><%= link_to 'Sign in', signin_path %>  </h2>
<% end %>

<%= render 'registration/signup' %>

app/views/users/index.html.erb
<h2>Index of all the users</h2>

<h4><%= link_to 'Home', root_path %></h4>

<% @users.each do |user| %>

  <p><%= link_to user.username, user_show_path(user) %> | <%= user.email %></p>

<% end  %>

app/views/users/new.html.erb
<%= render 'registration/signup' %>

app/views/users/show.html.erb
<h3>This is <%= @user.username %>'s page!</h3>
email: <%= @user.email %>
avatar: <%= image_tag(@user.avatar_url, class: "thumbnail small") %>

<%= form_for([@user, @gweet]) do |f| %>
		gWeet:
		<%= f.text_area :content %> 
		<%= f.submit  %>
<% end %>

<p>
	<h2>My gWeets:</h2>
	<% @gweets.each do |gweet| %>
	<p><%= gweet.content %></p>
	<% end  %>
</p>